### ISSUE TITLE
BUG002# กดเลือกRemember me ระบบไม่จำUser และ Password ที่เคยกรอกหน้าเว็บก่อนหน้านี้

### ISSUE THREAD

**Issue by Sun1212312121** [Sun1212312121/WebsitePTG_AWS#1]
![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/1d33393d-3dd3-433d-ac50-b7eb2c213641)

![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/73dc2e2b-74b3-407e-ade2-0d6ec381ad44)

**Comment by saowaros123** [comment]
ปิดฟังก์ชันนี้

![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/122771940/bbc6d62c-66f2-4883-b52c-63577bfe1923)
