### ISSUE TITLE
BUG008# เมื่อย้ายไปเลือกเมนูอื่นแล้ว เมนูย่อยของยั่งยืนยังเเสดงอยู่

### ISSUE THREAD

**Issue by Sun1212312121** [Sun1212312121/WebsitePTG_AWS#10]
หมายเหตุ : จากรูปอยูู่ในเมนูจัดจ้าง แต่แสดงเมนูย่อยยั่งยืน

![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/47e22424-fcb1-41aa-a729-b4833adc1332)

**Comment by saowaros123** [comment]
แก้ Phase2
