### ISSUE TITLE
BUG010# ไอคอลX ยังเป็น version เก่าอยู่

### ISSUE THREAD

**Issue by Sun1212312121** [Sun1212312121/WebsitePTG_AWS#11]
![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/3f4d0f1a-4a8f-4ed7-b93a-d82a868fabda)

**Comment by saowaros123** [comment]
แก้ไขเปลี่ยนไอคอนแล้ว

**Comment by Sun1212312121** [comment]
retest วันที่ 20/06  ผลการเทสยังไม่ผ่านค่ะ

![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/f9d97ace-5398-4472-89f9-934ce618c31a)

**Comment by Sun1212312121** [comment]
retest วันที่ 21/06 ผลการเทสยังผ่านค่ะ

![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/63390cbc-91d1-4856-ad47-d14d632e82ff)
