### ISSUE TITLE
BUG011# ไม่สามารถเข้าสู่ระบบ เมนูร่วมงานกับเราได้

### ISSUE THREAD

**Issue by Sun1212312121** [Sun1212312121/WebsitePTG_AWS#12]
หมายเหตุ : คลิกแล้วไม่มีอะไรเกิดขึ้น

![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/9d454c46-3cc3-4bec-950b-29101b0b89da)

**Comment by saowaros123** [comment]
ปิดฟังก์ชัน

**Comment by natchayaho** [comment]
https://github.com/Sun1212312121/WebsitePTG_AWS/assets/155532382/02ebcbf3-412c-43b4-aa50-ff6f35caf295

**Comment by Sun1212312121** [comment]
ผลการทดสอบผ่านค่ะ 



![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/9264c11c-77d3-47dc-8bf5-7dde62d7259e)
