### ISSUE TITLE
BUG012# ระบบไม่มีข้อความแจ้งเตือนเมื่อใส่ captcha code ผิด

### ISSUE THREAD

**Issue by Sun1212312121** [Sun1212312121/WebsitePTG_AWS#13]
![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/c96957e7-30b0-4a79-b042-1d5ee7ef660b)

**Comment by natchayaho** [comment]
![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/155532382/480e7799-f6a6-4d23-b8c9-e4901f408579)
![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/155532382/1fa7fe77-e30a-45e5-8550-33e1e5960fc0)

**Comment by Sun1212312121** [comment]
ผลการทดสอบผ่านค่ะ

![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/72226b9b-17d7-4ce7-9e9d-b526ed6d1307)


![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/7ca5fa09-f98f-45d4-b5c8-4b4dad34f7f7)
