### ISSUE TITLE
BUG013# เมื่อเข้ามาที่หน้าการคุ้มครองข้อมูลส่วนบุคคล แล้ว คลิ๊กกลับไปที่รู้จัก PTG แล้วไม่กลับไปหน้ารู้จัก PTG ให้

### ISSUE THREAD

**Issue by Sun1212312121** [Sun1212312121/WebsitePTG_AWS#14]
https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/94b1a4fb-6eb2-4f31-b10e-08eaaec271c4

**Comment by saowaros123** [comment]
https://github.com/Sun1212312121/WebsitePTG_AWS/assets/122771940/ed6a25f1-a0fb-4f88-b407-e460cb54dd70

**Comment by Sun1212312121** [comment]
ผลการทดสอบผ่านค่ะ



https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/6e3551a5-354a-4776-bf83-5cf267abadd6
