### ISSUE TITLE
BUG014 #  ลำดับการเข้าเมนูแสดงไม่ทั้งหมด

### ISSUE THREAD

**Issue by Sun1212312121** [Sun1212312121/WebsitePTG_AWS#15]
![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/e9a0a30d-eeb8-4155-9770-3f976c5747ce)

![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/d895ca39-279e-4012-b212-90d0e09f8397)

**Comment by saowaros123** [comment]
ยึดการแสดงลำดับข้อมูลตามนี้เนื่องจากเป็น format ที่ vendor ทำไว้ เฉพาะเมนูความยั่งยืน
