### ISSUE TITLE
BUG015# ระบบไม่กรองข้อมูลตำแหน่งงานให้เมื่อเลือกจังหวัด

### ISSUE THREAD

**Issue by Sun1212312121** [Sun1212312121/WebsitePTG_AWS#16]
![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/dfe98b9a-5fc4-456b-99cc-365f58932bb6)

![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/5b77d909-6b9d-462a-bc97-c33f61467bc8)

**Comment by saowaros123** [comment]
แก้ Phase2
