### ISSUE TITLE
BUG016# เมื่อทำการอัพโหลดไฟล์ ทำให้สมัครสมาชิกไม่ได้

### ISSUE THREAD

**Issue by Sun1212312121** [Sun1212312121/WebsitePTG_AWS#17]
![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/213dca75-3103-48e5-893a-60aabde6a881)

**Comment by natchayaho** [comment]
https://github.com/Sun1212312121/WebsitePTG_AWS/assets/155532382/601982fb-5a57-412a-beed-87aae8c19e09

**Comment by Sun1212312121** [comment]
ผลการทดสอบวันที่ 27/06 ยังได้ผลเทสตามเดิมค่ะ 


![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/c4376e91-3b0f-4598-a5bc-cf217710634c)

**Comment by natchayaho** [comment]
https://github.com/Sun1212312121/WebsitePTG_AWS/assets/155532382/f6e390dd-d48d-45a3-a991-bce22a287190

**Comment by Sun1212312121** [comment]
ผลการทดสอบผ่านแล้วค่ะ

![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/869ab207-3588-43f6-a56e-7d0e545e1a2e)



![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/5234a0b3-e0c2-4d72-80bc-cb79a041b43c)
