### ISSUE TITLE
BUG017#  กรอกช่องบังคับสมัครไม่หมด ไม่ขึ้นแจ้งเตือน

### ISSUE THREAD

**Issue by Sun1212312121** [Sun1212312121/WebsitePTG_AWS#18]
https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/ec38ca37-86cb-4d87-9c1a-1dc86d3dcb4d

**Comment by natchayaho** [comment]
https://github.com/Sun1212312121/WebsitePTG_AWS/assets/155532382/9b77de87-ab5e-45c3-9b79-1888a4ecd8f2

**Comment by Sun1212312121** [comment]
ผลการทดสอบยังไม่ผ่านค่ะ แจ้งเตือนยืนยันรหัสผ่านไม่ขึ้น 

https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/6df09ea4-df78-49fc-b7f5-4f72dcffe353

**Comment by natchayaho** [comment]
https://github.com/Sun1212312121/WebsitePTG_AWS/assets/155532382/a99524fa-4f62-463e-ac79-2f8b96c61af9

**Comment by natchayaho** [comment]
https://github.com/Sun1212312121/WebsitePTG_AWS/assets/155532382/130a7404-a905-4430-b04e-50736eb1aedc

**Comment by Sun1212312121** [comment]
ผลการทดสอบยังไม่ผ่านค่ะ ระบบไม่มีการแจ้งเตือนเรื่องรหัสผ่านยืนยันไม่ตรงกันค่ะ


https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/a562ea2c-8166-49fe-9935-36371974cb6e

**Comment by Sun1212312121** [comment]
ผลการทดสอบผ่านแล้วค่ะ


![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/463c9991-78af-4958-a310-19ea975c7e50)


![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/f984b152-7185-47ed-a553-2a30f46c762c)




![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/873137ba-47fc-499e-9492-9a69d965e5f4)
