### ISSUE TITLE
BUG001# กดยอมรับนโยบายคุกกี้ไปแล้ว คุกกี้ขึ้นอีก

### ISSUE THREAD

**Issue by Sun1212312121** [Sun1212312121/WebsitePTG_AWS#2]
https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/aa31360f-7fe1-47f3-9b31-8b1225489541

**Comment by saowaros123** [comment]
https://github.com/Sun1212312121/WebsitePTG_AWS/assets/122771940/f9bc9dd2-0fbb-4038-9700-c516a6961e0b

**Comment by Sun1212312121** [comment]
ผลการทดสอบผ่านค่ะ


![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/0a8baafe-17e8-445f-91a1-4d398736d33e)


![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/33adf211-25ee-4911-b4f3-147faf4a05bd)
