### ISSUE TITLE
BUG019# หัวข้อเรื่องที่คุณอาจสนใจอื่นๆ แสดงซำ้

### ISSUE THREAD

**Issue by Sun1212312121** [Sun1212312121/WebsitePTG_AWS#20]
หน้าแรก > กิจกรรมเพื่อสังคม > ข่าวกิจกรรมเพื่อสังคม

![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/c620139d-41c8-4c39-9ada-f78c7b4eb4bb)

**Comment by saowaros123** [comment]
https://github.com/Sun1212312121/WebsitePTG_AWS/assets/122771940/cdafb05b-c3a5-415c-9b93-ccb7726113e2

**Comment by Sun1212312121** [comment]
ผลการทดสอบ ผ่านค่ะ 

![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/5bcd026b-e6f0-4d17-a5f0-13731117ce7f)
