### ISSUE TITLE
BUG004#เมนูนักลงทุนสัมพันธ์ พอแก้แล้วกด SAVE มันเปลี่ยนกลับเป็นแบบเดิม แบบก่อนแก้

### ISSUE THREAD

**Issue by Sun1212312121** [Sun1212312121/WebsitePTG_AWS#21]
![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/707c9211-7c86-4ac9-a4eb-9f16c4f28d80)

![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/0b8c071a-aad3-4036-92d7-e73090149627)

**Comment by saowaros123** [comment]
แก้ Phase2
