### ISSUE TITLE
BUG020# เมื่อกดเมนูความยั่งยืนคืออะไรไปแล้วไม่เจอข้อมูล

### ISSUE THREAD

**Issue by Sun1212312121** [Sun1212312121/WebsitePTG_AWS#24]
หน้าแรก > ความยั่ง > การบริหารจัดการด้านความยั่งยืนองค์กร > ความยั่งยืนคืออะไร

![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/9ca65835-7506-4848-84cc-b20f4b3d1afe)

![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/f7e2988b-3eb0-4602-8892-a0601cdcbb70)

**Comment by saowaros123** [comment]
ถ้าตรงนี้จะเป็นส่วนเมนู สามารถเลือกรูปแบบการแสดงได้ นอกจากจะเพิ่มเนื้อหาข้างในถึงจะมีข้อมูล เช่น ถ้าเลือกหัวข้อเมนูก็จะแสดงเฉพาะเมนู



![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/122771940/fabceb3f-059a-4175-b69b-bee5ecdc5d67)
![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/122771940/17e72448-5d3b-4cbb-b343-98904e992393)
![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/122771940/56aaf00d-865d-485b-b034-cc41f0bba9d0)

**Comment by Sun1212312121** [comment]
ผลการทดสอบผ่านค่ะ

![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/9aa9c6b9-ad62-4911-89f1-21e24484329f)


![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/6369e29b-84d9-42ee-9467-d96b75146196)
