### ISSUE TITLE
BUG21# กดเมนูมิติด้านเศรษฐกิจเป็นหน้าสีขาว

### ISSUE THREAD

**Issue by Sun1212312121** [Sun1212312121/WebsitePTG_AWS#25]
หน้าแรก > ความยั่งยืน > มิติด้านเศรษฐกิจ

![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/e2d8590b-1e78-4571-8b04-00f8856b8269)

![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/a70c76a2-6c05-40c7-bac0-9312eab7cb9a)

**Comment by saowaros123** [comment]
![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/122771940/fccd2d06-230c-4af9-97d5-e40b4d17e78f)

**Comment by Sun1212312121** [comment]
ผลการทดสอบผ่านค่ะ 


![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/c3b9799d-6cc0-4860-8ef7-0850425597b8)
