### ISSUE TITLE
BUG006# [หน้าแรก] [Edit menu] กด approve ที่หน้า edit menu แล้ว pop up approve ไปแสดงอยู่ข้างหลัง edit menu

### ISSUE THREAD

**Issue by B95krk** [Sun1212312121/WebsitePTG_AWS#26]
คิดว่ามันควรจะขึ้นมาแสดงทั้บ edit menu ไหม หรือ ปิดหน้า edit menu ไปเลยตอนกดปุ่ม approve

![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/153166795/6416dc77-4f45-4218-99d0-40a2e14eb224)

**Comment by saowaros123** [comment]
ยังคงยืดการแสดง approve ไปแสดงอยู่ข้างหลัง edit menu ตามเดิม
