### ISSUE TITLE
BUG007# [หน้าแรก] [Edit menu] Section Upload รูปภาพหายไป

### ISSUE THREAD

**Issue by B95krk** [Sun1212312121/WebsitePTG_AWS#27]
step 
1 เปิด edit menu 
2 กดลบรูปภาพ > กด save 
3 เปิด edit menu อีกครั้งเป็นรอบที่ 2
4 กดลบรูปภาพ > กด save อีกครั้ง
5 เปิด edit menu อีกครั้งเป็นรอบที่ 3
6 section upload รูปภาพจะหายไป

![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/153166795/c9a8019c-bf09-4267-af17-192d3bae4156)

**Comment by saowaros123** [comment]
แก้ Phase2
