### ISSUE TITLE
BUG008# ปุ่ม save หมุนค้างและใช้งานไม่ได้ 

### ISSUE THREAD

**Issue by B95krk** [Sun1212312121/WebsitePTG_AWS#28]
Step
1 เปิด edit menu
2 เพิ่มรูปภาพที่ไม่ใช้ไฟล์ JPG, PNG > กด save
3 แสดง popup error
4 ปุ่ม Save หมุนค้าง และ กดไม่ได้ ต้องรีเฟรชหน้านี้เท่านั้นถึงจะใช้งานได้

![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/153166795/22fb7f67-b2d0-484a-b2d5-bb12cef4ea84)

 Step
1 เปิด edit menu  รู้จัก พี่ที่จี >  เมนูย่อยที่ตั้งสำนักงานใหญ่
2 แก้ไขข้อความในช่อง
43ปุ่ม Save หมุนค้าง และ กดไม่ได้ ต้องรีเฟรชหน้านี้เท่านั้นถึงจะใช้งานได้

![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/470b7ce5-861f-402e-9cb7-e76333084624)

**Comment by saowaros123** [comment]
ในส่วนของการเช็คนามสกุล JPG, PNG จะเป็น แก้ Phase2 ส่วนเคสที่สองลองทำการทดสอบสามารถแก้ไขข้อความในช่องได้ 

![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/122771940/aff081cb-301f-40aa-820a-20c2210eec54)

**Comment by saowaros123** [comment]
ทำการแก้การเช็ค นามสกุลไฟล์แล้ว 


https://github.com/Sun1212312121/WebsitePTG_AWS/assets/122771940/40d0a036-4981-44ae-af2d-da5ccac70c67



ส่วนเคสที่สองลองทำการทดสอบสามารถแก้ไขข้อความในช่องได้

**Comment by Sun1212312121** [comment]
Step
1 เปิด edit menu
2 เพิ่มรูปภาพที่ไม่ใช้ไฟล์ JPG, PNG > กด save
3 แสดง popup error
4 ปุ่ม Save หมุนค้าง และ กดไม่ได้ ต้องรีเฟรชหน้านี้เท่านั้นถึงจะใช้งานได้
**** ผลการทดสอบผ่านแล้วค่ะ *****
![image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/bbb33a07-ab2e-438e-b666-18bdeea182c0)


Step
1 เปิด edit menu รู้จัก พี่ที่จี > เมนูย่อยที่ตั้งสำนักงานใหญ่
2 แก้ไขข้อความในช่อง
3. ปุ่ม Save หมุนค้าง และ กดไม่ได้ ต้องรีเฟรชหน้านี้เท่านั้นถึงจะใช้งานได้
***** ผลการทดสอบผ่านแล้วค่ะ ******
![image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/6805acef-031b-45a5-85a0-420f5fcb002f)
