### ISSUE TITLE
BUG022# ไม่สามารถเปิดไฟล์ pdf ได้

### ISSUE THREAD

**Issue by Sun1212312121** [Sun1212312121/WebsitePTG_AWS#29]
หัวข้อดังนี้
1. หน้าแรก > ความยั่งยืน > เศรษฐกิจ > มิติด้านเศรษฐกิจ> การกำกับดูแลกิจการ > ไฟล์ตรวจสอบข้อมูลไฟล์ PDF นโยบายภาษี
2. หน้าแรก > ความยั่งยืน > เศรษฐกิจ >การบริหารห่วงโซ่อุปทาน  > ไฟล์จรรยาบรรณธุรกิจสำหรับบริษัทคู่ค้า
3. หน้าแรก > ความยั่งยืน > สังคม > สิทธิมนุย> การบริหารจัดการด้านสิทธิมนุษยชน > ไฟล์นโยบายคุ้มครองข้อมูลส่วนบุคคล
4. หน้าแรก > ความยั่งยืน >สังคม > สิทธิมนุย> การประเมินความเสี่ยงด้านสิทธิมนุษยชน > ไฟล์การประเมินความเสี่ยงด้านสิทธิมนุษยชน
5. หน้าแรก > ความยั่งยืน >สิ่งแวดล้อม >  การบริหารจัดการด้านสิ่งแวดล้อม > หัวข้อไฟล์ นโยบายคุณภาพ ความมั่นคง ความปลอดภัย อาชีวอนามัย และสิ่งแวดล้อม

![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/5fca0f43-398e-4352-a68e-9cb34ae97edb)

6. หน้าแรก > ความยั่งยืน >  สถิติการดำเนินงานด้านความยั่งยืน> การบริหารจัดการด้านสิ่งแวดล้อม >ไฟล์นโยบายด้านบรรจุภัณฑ์ที่ยั่งยืน
7. หน้าแรก > ความยั่งยืน > รายงานความยั่งยืน >สถิติการดำเนินงานด้านความยั่งยืน>  ไฟล์สถิติการดำเนินงานด้านความยั่งยืน

ทุกๆหัวข้อดาว์โหลดดูไฟล์ไม่ได้ขึ้นแบบนี้หมดเลย
![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/60065f54-9a13-423a-bd37-c857322db61f)

**Comment by natchayaho** [comment]
หน้าแรก > ความยั่งยืน >มิติด้านเศรษฐกิจ> การกำกับดูแลกิจการ > ไฟล์ตรวจสอบข้อมูลไฟล์ PDF การด้านภาษี

![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/155532382/472a6872-b47a-4f1b-b90f-8390b41c4d69)
![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/155532382/8659d72a-4e88-4ae5-9b94-69d62099312d)

**Comment by Sun1212312121** [comment]
ผลทดสอบยังไม่อัพโหลดไฟล์ได้หลายหัวข้อ รบกวนตรวจสอบให้ครบทุกหัวข้อ หรือถ้ามีวิธีอื่นๆที่สามารถเปิดไฟล์หัวข้อนั้นๆได้ รบกวนระบุให้ชัดเจนด้วยนะคะ

**Comment by saowaros123** [comment]
แก้ไขและทำการทดสอบแล้ว รบกวนตรวจสอบอีกครั้ง

**Comment by Sun1212312121** [comment]
หน้าแรก > ความยั่งยืน > เศรษฐกิจ > มิติด้านเศรษฐกิจ> การกำกับดูแลกิจการ > ไฟล์ตรวจสอบข้อมูลไฟล์ PDF นโยบายภาษี   ไฟล์ดาว์โหลดหายไป

**Comment by Sun1212312121** [comment]
ผลการทดสอบผ่านแล้วค่ะ

![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/f8018a75-2f3b-4e77-a477-87fac190aa87)
