### ISSUE TITLE
BUG002# เปลี่ยนภาษาเป็นอังกฤษไม่ได้

### ISSUE THREAD

**Issue by Sun1212312121** [Sun1212312121/WebsitePTG_AWS#3]
![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/e97f8007-a0e0-4707-950e-f94907577d68)

**Comment by natchayaho** [comment]
https://github.com/Sun1212312121/WebsitePTG_AWS/assets/155532382/2b68ae43-8dd7-4e4a-965f-1c3dbaf87b1c

**Comment by Sun1212312121** [comment]
ผลการทดสอบไม่ผ่านค่ะ 


![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/b4a20272-565f-4998-bbb5-7ac9bafbd91d)

**Comment by saowaros123** [comment]
แก้ Phase2 เนื่องจากเป็น bug เก่าบน production 


![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/122771940/cf457737-7787-433b-bcf4-f586bd7aa08c)
![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/122771940/542c59a8-eb15-424f-9b13-c41578389e34)
