### ISSUE TITLE
BUG009#  [หน้าร่วมกับเรา] [กลุ่มธุรกิจ] [Edit business] ปรับสถานะที่หน้า Edit menu แสดง popup error

### ISSUE THREAD

**Issue by B95krk** [Sun1212312121/WebsitePTG_AWS#30]
แต่เลือกจาก Dropdown ของหน้า กลุ่มธุรกิจได้ปกติ

![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/153166795/0f925e44-baa5-4219-b0ac-8d040628aeae)

**Comment by saowaros123** [comment]
![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/122771940/a2fac828-667b-4548-9c4c-c6b541abd69f)
![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/122771940/ee27cb16-73a3-40fa-aa11-cbc0306280a3)

**Comment by Sun1212312121** [comment]
ผลการทดสอบผ่านแล้วค่ะ 
![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/2b247c53-7e1b-41f0-ac2e-aef910b192b0)
