### ISSUE TITLE
BUG010# [รวมงานกับเรา][ตำแหน่งงานทั้งหมด] กดแก้ไขแล้ว ไม่สามารถกดบันทึกได้ เนื่องจากเลือกข้อมูลแล้ว ข้อมูลไม่ทำการจำค่าที่เลือก

### ISSUE THREAD

**Issue by Sun1212312121** [Sun1212312121/WebsitePTG_AWS#31]
https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/6f1b3f3b-57d1-49d5-b4f9-8677d4743db4

**Comment by saowaros123** [comment]
![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/122771940/f24f78f1-547c-4475-9e26-56ac891345ce)

**Comment by Sun1212312121** [comment]
ผลการทดสอบผ่านค่ะ

![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/f3983607-9c49-4136-8a3e-1d9218bacf0a)
