### ISSUE TITLE
BUG011# upload รูปภาพที่ไม่ใช่ไฟล์ png. หรือ jpg  erorr ผิด

### ISSUE THREAD

**Issue by Sun1212312121** [Sun1212312121/WebsitePTG_AWS#32]
1. แก้ไขเมนูหลัก รู้จักพีทีจี  
2.  เมนูหลักรู้จักพีทีจี>การกำกับดูแลกิจการที่ดี>  โครงสร้างองค์กร
3.  เมนูหลักรู้จักพีทีจี>คลังน้ำมัน
Expected Result :  ระบบแจ้งเตือน "Only supports png and jpg extensions"

ตัวอย่างเช่น

![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/3799fedd-3f1e-4104-a326-1126cad5e9e8)

**Comment by saowaros123** [comment]
แก้ Phase2

**Comment by saowaros123** [comment]
https://github.com/Sun1212312121/WebsitePTG_AWS/assets/122771940/10d82cbc-612c-4e9b-9d59-a09918ec4b1c

**Comment by Sun1212312121** [comment]
ช่วย confirm กับ User ให้หน่อยค่ะว่าใช้ Erorr  erorr Only supports png and jpg extensions หรือ  erorr Invalid file extension

**Comment by Sun1212312121** [comment]
ผลการทดสอบผ่านแล้วค่ะ

แก้ไขเมนูหลัก รู้จักพีทีจี

![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/2368f6e2-1b71-4d0e-85b1-1131c46a29c3)


เมนูหลักรู้จักพีทีจี>การกำกับดูแลกิจการที่ดี> โครงสร้างองค์กร
![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/81211bf7-ade8-46f0-b523-fd2ecef6117b)

เมนูหลักรู้จักพีทีจี>คลังน้ำมัน
![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/a5a0eb8c-111d-482f-8224-61c75806688a)
