### ISSUE TITLE
BUG#012 [ร่วมงานกับเรา][ประเภทงาน] แก้ไขข้อมูลไม่ได้

### ISSUE THREAD

**Issue by Sun1212312121** [Sun1212312121/WebsitePTG_AWS#33]
https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/367e7f41-4cdc-4e41-8654-8acec4966840

**Comment by saowaros123** [comment]
![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/122771940/75a76524-d0f1-4f73-a234-134814b69c93)

**Comment by Sun1212312121** [comment]
ผลการทดสอบผ่านค่ะ 

![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/89943c2d-e3f3-4e9d-888c-3ab7d1c84383)



![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/7ffbbb29-39a1-42ad-8650-c97e59019ff6)
