### ISSUE TITLE
BUG013#  เพิ่มเมนูย่อย รู้จักพีทีจี แล้วหน้าเว็บไซต์Front endไม่แสดงเมนู

### ISSUE THREAD

**Issue by Sun1212312121** [Sun1212312121/WebsitePTG_AWS#34]
![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/9d370d62-a137-4ba4-b73d-9b3e63e738fb)

![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/85b385c0-ba63-4919-82d9-3dde86646477)

**Comment by Sun1212312121** [comment]
![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/ac040f5f-0826-428a-b42e-df1940c209ce)

**Comment by saowaros123** [comment]
![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/122771940/81c89f87-3d22-4bb1-bfac-4ccd98d2ea8c)
![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/122771940/440582f0-d1c3-45c7-b90c-37ceb2ec31af)
![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/122771940/24172343-b756-4dca-9e9b-195d5d717e53)
