### ISSUE TITLE
BUG014# [หน้าแรก] [Banner] [Edit menu] เงื่อนไขของ cancel ทำงานไม่ถูกต้องเมื่อลบข้อมูลที่เป็น content

### ISSUE THREAD

**Issue by B95krk** [Sun1212312121/WebsitePTG_AWS#35]
Step
1 เปิด edit menu ของ banner
2 กด check box > กดปุ่มลบข้อมูล > กดปุ่ม Delete
3 กดปุม cancel
4 เปิด edit menu ของ banner รอบที่ 2 

= จะเห็นว่าข้อมูลที่กดลบไปมันไม่แสดงขึ้นมาอีกเลย ซึ่งมันควรแสดงเพราะยังไม่ได้กดปุ่ม save แต่กดปุ่ม cancel

**Comment by saowaros123** [comment]
แก้ Phase2
