### ISSUE TITLE
BUG015# [ร่วมกับเรา][เพิ่มตำแหน่งงานทั้งหมด] ทำการ Inactive ประเภทงานแล้วยังคงแสดงอยู่

### ISSUE THREAD

**Issue by Sun1212312121** [Sun1212312121/WebsitePTG_AWS#36]
![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/cefcc1a2-45e9-4155-89ce-c9f826d7e956)

ที่Back office ยังแสดงอยู่
![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/0e686a4a-1ed2-455a-bb43-8d34b7575d9d)

 แต่ที่ Front-End ไม่แสดงแล้ว

![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/9e5e728b-b6f0-457d-a3e9-d5c641595e8e)

**Comment by saowaros123** [comment]
![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/122771940/2545c841-02c9-4b8c-aef5-1b31cdd7262e)
![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/122771940/49d9c00c-0c75-4969-b873-618de9e90d6e)
![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/122771940/b7b14dea-8d18-480b-ae77-a532260a42e5)

**Comment by Sun1212312121** [comment]
ผลการทดสอบผ่านค่ะ

![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/aad4cee1-b29e-4fad-81c3-2a9e5e47ba03)



![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/72102b12-4f45-4c6f-acc0-df2fbb8b0e28)



![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/a2799cbb-e4a1-419c-8544-adc27ba6c662)
