### ISSUE TITLE
BUG016# [ฝ่าย] ทำการแก้ไขสถานะของฝ่าย จาก active เป็น inactive และแก้จาก inactive คืนเป็น active  ไม่สามารถทำได้

### ISSUE THREAD

**Issue by pongsakornja** [Sun1212312121/WebsitePTG_AWS#37]
https://github.com/Sun1212312121/WebsitePTG_AWS/assets/135002790/7804f8dc-8132-4395-bfa2-8f327fbaee00

**Comment by saowaros123** [comment]
![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/122771940/6ce9589f-0b9d-4671-b5d7-2096d8c9e8c3)

**Comment by Sun1212312121** [comment]
ผลการทดสอบผ่านค่ะ 

![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/1b10718d-7ca3-45ab-abfb-f98d700c07c5)



![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/403d4bd5-7330-4162-bcfb-d7473e6b2333)



![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/2f1e1671-10c1-46ed-9754-006943245e8b)
