### ISSUE TITLE
BUG017# [หน้าแรก] [Banner] [Edit menu] [Edit content] Section Upload หายไป

### ISSUE THREAD

**Issue by B95krk** [Sun1212312121/WebsitePTG_AWS#38]
Step 
1 เปิด Edit menu ที่ Banner
2 กดปุ่ม แก้ไขข้อมูล
3 กดลบรูปภาพ > กดปุ่ม OK
4 กดปุ่ม แก้ไขข้อมูล รอบที่ 2 

= จะเห็นว่าถ้าเราลบรูปเก่าออกไปแล้วกด ok เราจะไม่สามารถเพิ่มรูปภาพอีกครั้งได้เลย

![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/153166795/08018224-760b-4c36-b0fa-e8490756d2fb)

**Comment by saowaros123** [comment]
แก้ Phase2
