### ISSUE TITLE
BUG18#  เพิ่มชื่อคณะกรรมการบริษัท ไม่ขึ้นหน้าเว็บ Front-End

### ISSUE THREAD

**Issue by Sun1212312121** [Sun1212312121/WebsitePTG_AWS#39]
![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/863decdc-9d16-4a41-a05e-48e85abace20)

![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/c04099a5-26d9-4b8f-ac88-98fc4c434ca4)

![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/97458de3-eea2-4554-a221-b1e282d61f12)

**Comment by saowaros123** [comment]
![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/122771940/19f20699-e4f5-4445-a8b2-57b91ca33947)
![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/122771940/a2bf4bd9-e512-420d-84ac-8958348cbc68)

**Comment by Sun1212312121** [comment]
ผลการทดสอบผ่านค่ะ 

![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/b4168fbc-4fba-4d40-b6a4-fccbe09b856e)


![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/d7b504c5-a34e-4f6f-86e5-b484e3b27e42)
