### ISSUE TITLE
BUG003# ปุ่มค้นหาใช้งานค้นหาข้อมูลไม่ได้

### ISSUE THREAD

**Issue by Sun1212312121** [Sun1212312121/WebsitePTG_AWS#4]
![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/bbe74371-f385-4f02-ba8d-70f852c8c026)

**Comment by saowaros123** [comment]
ทำการปิดปุ่มนี้แล้ว เนื่องจากใช้งานไม่ได้มาสักพักแล้ว แจ้ง user รับทราบแล้ว
