### ISSUE TITLE
BUG019# [หน้าแรก] [Banner] [Edit menu] [Edit content] แสดง message error ไม่ถูกต้องเมื่ออัพไฟล์ PDF ในช่องรูปภาพ

### ISSUE THREAD

**Issue by B95krk** [Sun1212312121/WebsitePTG_AWS#40]
= ถ้าอัพรูปภาพในช่อง PDF จะแสดง Only supports png and jpg extensions แต่ถ้าอัพไฟล์ PDF ในช่องของรูปภาพจะแสดงเป็นอีกแบบตามรูปภาพ

![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/153166795/b38a59fa-2b30-4f08-b5d7-4004567f26b5)

**Comment by natchayaho** [comment]
![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/155532382/048ce075-7207-4861-9525-a1d3054b15c4)

สามารถอัพโหลดได้เฉพาะไฟล์รูปภาพ เนื่องจากเป็น image ไม่สามารถอัพไฟล์ pdf ได้

**Comment by natchayaho** [comment]
![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/155532382/549538c0-09bc-4753-abbc-7323a530ca43)

สามารถอัพโหลดได้เฉพาะไฟล์ pdf ในช่องอัพโหลด pdf เนื่องจากมีการเขียนเงื่อนไขกำหนดเฉพาะไว้แล้ว

**Comment by Sun1212312121** [comment]
ผลการทดสอบผ่านแล้วค่ะ
![image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/8310169f-5910-4f1e-bfd0-39832f6faafd)
