### ISSUE TITLE
BUG020# [หน้าแรก] [Banner] [Edit menu] [Edit content] ปุ่มลบข้อมูลยังแสดงอยู่เมื่อไม่มีข้อมูลให้ลบหรือไม่ได้กด Checkbox

### ISSUE THREAD

**Issue by B95krk** [Sun1212312121/WebsitePTG_AWS#41]
Step
1 เปิดหน้าแรก 
2 ไปที่ Edit menu ของ banner
3 กด checkbox > กดปุ่ม ลบข้อมูล > กดปุ่ม Delete

= จะเห็นว่าปุ่ม ลบข้อมูลยังคงแสดงอยู่และสามารถกดเล่นได้เรื่อยๆ 
 
![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/153166795/6be08dd6-fc7c-4916-9ac3-d1dc57686d6f)

**Comment by saowaros123** [comment]
https://github.com/Sun1212312121/WebsitePTG_AWS/assets/122771940/1d302e3f-0cee-4867-a249-a7900651096e

**Comment by Sun1212312121** [comment]
***** ผลการทดสอบผ่านแล้วค่ะ *****
![image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/09802e95-118b-423e-8a6b-fcba48e5f3fa)
