### ISSUE TITLE
BUG021# [หน้าแรก] [Image Popup] [Edit Manage Popup] ไม่แสดงปุ่ม Approve ให้กดหลังจากกด save

### ISSUE THREAD

**Issue by B95krk** [Sun1212312121/WebsitePTG_AWS#42]
![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/153166795/e6a87c69-0281-4dc7-8a0c-651847a8464b)

**Comment by saowaros123** [comment]
แก้ Phase2
