### ISSUE TITLE
BUG022# [หน้าแรก] [Image Popup] [Edit Manage Popup] ไม่สามรถเพิ่มไฟล์ PDF ใน image popup

### ISSUE THREAD

**Issue by B95krk** [Sun1212312121/WebsitePTG_AWS#43]
![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/153166795/8e86d2c7-cd5e-48d6-8395-2a806c26c763)

**Comment by natchayaho** [comment]
![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/155532382/a3cc2dfa-2e48-493e-a6bd-06064cca9431)

สามารถอัพโหลดได้เฉพาะไฟล์รูปภาพ เนื่องจากเป็น image popup ไม่สามารถอัพไฟล์ pdf ได้

**Comment by Sun1212312121** [comment]
issus ข้อเดียวกับ BUG003
