### ISSUE TITLE
BUG023 # อัพวิดีโอไปใหม่ ไม่แสดงที่หน้าเว็บ

### ISSUE THREAD

**Issue by Sun1212312121** [Sun1212312121/WebsitePTG_AWS#45]
รบกวนตรวจสอบว่าเป็น fixcode ไหม สามารถแก้วีดีโอหลังบ้านได้ไหม  แล้วที่อัพโหลดในเว็บหลังบ้านจะแสดงที่ไหนในเว็บ Front End
![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/02528b62-a2fa-4f1f-89f3-6f7175c5dd31)

![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/eb5ade40-1cf3-4c6b-a469-7a089a4a2f12)

**Comment by saowaros123** [comment]
ส่วนนี้เป็น fix code ค่ะ

![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/122771940/0d7edb96-2312-44e3-8279-78b0045ee852)
