### ISSUE TITLE
Bug006# กดเมนูแจ้งเบาะแสการทุจริต  ส่วนFooter  ลิงค์ข้อมูลผิด

### ISSUE THREAD

**Issue by Sun1212312121** [Sun1212312121/WebsitePTG_AWS#7]
![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/bebbf0c7-2bc6-4c33-b876-b02364a7aa9e)

**Comment by saowaros123** [comment]
https://github.com/Sun1212312121/WebsitePTG_AWS/assets/122771940/1f0e64a3-d3b5-4bb6-8704-c16fbd5b77c4

**Comment by Sun1212312121** [comment]
ผลการ retest 27/06 ผ่านค่ะ
![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/17ea609d-2ae6-4a68-bf3b-9ae2be296e8c)
