### ISSUE TITLE
Bug007# กดเงื่อนไขการใช้เว็บไซต์/ที่ตั้งสำนักงานใหญ่ ส่วนส่วนท้ายสุดของเว็บไซต์ลิงค์ข้อมูลอยู่หน้าเดิม

### ISSUE THREAD

**Issue by Sun1212312121** [Sun1212312121/WebsitePTG_AWS#8]
![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/26ec029a-49b5-41bb-9c8f-34df8132d7a1)

![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/4ce8ade1-440a-487f-9907-ae733150e70e)

**Comment by saowaros123** [comment]
ทำการปิด เงื่อนไขการใช้เว็บไซต์ แล้วเนื่องจากไม่มีข้อมูลและใช้งานไม่ได้มาสักระยะแล้ว ส่วนที่ตั้งสำนักงานใหญ่ ทำการแก้ไขเพิ่มลิงค์แล้ว

**Comment by Sun1212312121** [comment]
ผลการทดสอบผ่านแล้วค่ะ
