### ISSUE TITLE
BUG003# Popup เมนูหน้าแรกอัพโหลดรูปภาพไม่ได้

### ISSUE THREAD

**Issue by Sun1212312121** [Sun1212312121/WebsitePTG_AWS#9]
![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/ff2edaae-eef1-4c77-9149-c56ea7ad71a7)

**Comment by saowaros123** [comment]
![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/122771940/c5d635a8-9899-4f0e-afb7-4487084bd684)

**Comment by Sun1212312121** [comment]
ผลการทดสอบผ่านค่ะ


![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/22689e24-6bb5-46b0-a015-aee204836a70)

![Image](https://github.com/Sun1212312121/WebsitePTG_AWS/assets/140136077/25c63e91-cdeb-4e24-a6d2-44dc4f7a9eef)
